all:
  hosts:
    bind00:
      ansible_host: 192.168.0.220
      ansible_user: labadmin
      ansible_password: '{{ lookup("env", "LABADMIN_PASSWORD") }}'
    nuk:
      ansible_host: 192.168.0.243
      ansilbe_user: vburich
      ansible_password: '{{ lookup("env", "VBURICH_PASSWORD") }}'
    nuk2:
      ansible_host: 192.168.0.244
      ansible_user: vburich	
      ansible_password: '{{ lookup("env", "VBURICH_PASSWORD") }}'
  children:
    allservers:
      hosts:
        bind00:
        nuk:
        nuk2:
