all:
  hosts:
    bind00:
      ansible_ssh_host: 192.168.0.220
      ansible_user: labadmin
    nuk:
      ansible_ssh_host: 192.168.0.243
      ansilbe_user: vburich
    nuk2:
      ansible_ssh_host: 192.168.0.244
      ansible_user: vburich	
  children:
    allservers:
      hosts:
        bind00:
        nuk:
        nuk2:
